### ISSUE TITLE
显示直播间主播名称

### ISSUE THREAD

**Issue by draymondgewade** [larvata/gyaruppi#34]
你好 能不能在显示直播间的名字的基础上显示主播的名字, 因为直播间的名字不是固定的, 有时候辨认不出是哪个主播的直播

**Comment by larvata** [comment]
由于不是所有平台都可以单独设置直播间名字
为了避免ui改动
直播间名字和主播名字不一致的场景 
会将主播名字显示在tooltip里

<img width="204" alt="image" src="https://github.com/larvata/gyaruppi/assets/1443833/adf6210e-9c46-489f-89b4-0cac8159a140">
